config/routes.rb
Rails.application.routes.draw do
  get '/entries', to: 'entries#index'
  get 'pages/index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/timeline', to: 'users#timeline', as: 'timeline'
  get '/symptoms_analysis', to: 'users#insight', as: 'symptom_analysis'
  get '/popup', to: 'users#popup'
  get '/hovercard', to: 'users#hovercard', as: 'hovercard'
  resources :symptoms
  resources :medications
  resources :moods
  resources :foods
  resources :drinks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<div class="d-flex entries signup_div pb-5 justify-content-center">
  <div class="w-50">
    <div class="bg-white pb-5 item-cont">
      <div class='w-100 header d-flex gap-2 gap-md-4 align-items-center justify-content-center'>
        <h4 class='para text-white mb-0'>Log Events</h4>
      </div>
      <div class="enter">
        <div class="items d-flex ml-5 gap-3 py-3 align-items-center">
          <%= svg_tag "Food"%>
          <%= link_to 'Meal/food', new_food_path, class: '' %>
        </div>
        <div class="d-flex items gap-3 py-3 align-items-center">
          <%= svg_tag "Drink"%>
          <%= link_to 'Drink', new_drink_path, class: '' %>
        </div>

        <div class="d-flex items gap-3 py-3 align-items-center">
          <%= svg_tag "Mood"%>
          <%= link_to 'Mood', new_mood_path, class: '' %>
        </div>

        <div class="d-flex items py-3 gap-3 align-items-center">
          <%= svg_tag "Medication"%>
          <%= link_to 'Medication', new_medication_path, class: '' %>
        </div>

        <div class="d-flex items py-3 gap-3 align-items-center">
          <%= svg_tag "Symptom"%>
          <%= link_to 'Symptom', new_symptom_path, class: '' %>
        </div>
      </div>
      <div class="cancel">
        <%= link_to '<i class="fa-sharp fa-solid fa-xmark"></i>'.html_safe, timeline_path, class: "go-to-entries position-fixed border-0" %>
      </div>
    </div>
  </div>
</div>