config/routes.rb
Rails.application.routes.draw do
  get '/entries', to: 'entries#index'
  get 'pages/index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/timeline', to: 'users#timeline', as: 'timeline'
  get '/symptoms_analysis', to: 'users#insight', as: 'symptom_analysis'
  get '/popup', to: 'users#popup'
  get '/hovercard', to: 'users#hovercard', as: 'hovercard'
  resources :symptoms
  resources :medications
  resources :moods
  resources :foods
  resources :drinks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/drink.rb
class Drink < ApplicationRecord
  has_rich_text :comment
  belongs_to :user
  validates :name, presence: true
  EDITABLE_ATTRS = %i[comment name date time].freeze
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /drinks or /drinks.json
  def index
    @user = current_user
    @drinks = Drink.all.order('created_at DESC').where(user: current_user)
  end

  # GET /drinks/1 or /drinks/1.json
  def show; end

  # GET /drinks/new
  def new
    @user = current_user
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit; end

  # POST /drinks or /drinks.json
  def create
    @user = current_user
    @drink = @user.drinks.build(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to timeline_path, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1 or /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to timeline_path, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1 or /drinks/1.json
  def destroy
    @drink.destroy

    respond_to do |format|
      format.html { redirect_to timeline_path, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_drink
    @drink = Drink.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def drink_params
    params.require(:drink).permit(:name, :comment, :time, :date, :user_id)
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/_drink.html.erb
<section class="gradient-custom-5">
  <div class="container">
    <div class="main-timeline-5">
      <div class="timeline-5 right-5">
        <div class="">
          <div class="card-body p-4">
            <%= svg_tag "Drink", class: "show-icon"%>
            <h5 class="card-title">Drink</h5>
            <h5><%= drink.name %></h5>
            <span class="small text-muted"><i class="fas fa-clock me-1"></i><%= drink.date.strftime("%F") %>|<%= drink.time.strftime("%H:%M") %></span>
            <p class="mt-2 mb-0"><%= drink.comment %></p>
            <%= link_to "View Details", drink, class: "view btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/drinks/_form.html.erb
<div id="<%= dom_id drink %>">
  <%= form_with(model: drink) do |form|%>
    <% if drink.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

        <ul>
          <% drink.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="position-relative">
      <div class="col-md-8 mx-auto pb-5 bg-light">
        <header class="text-center header w-100 medication px-4 text-light d-flex justify-content-between align-items-center">
          <p class="mb-0"> <%= link_to '<i class="text-white fa-solid fa-arrow-left"></i>'.html_safe, entries_index_path %></p>        <p class="mb-0 mx-auto d-flex align-items-center text-white">
          <%= svg_tag "Drink", class: "form-icon"%>
          <span>Drink</span>
        </p>
        </header>
        <div class="px-4 pb-4 pt-4 d-flex flex-column flex-md-row justify-content-md-between">
          <div class="flex-child-cont px-5">
            <div class="d-flex justify-content-between">
               <div class="d-block">
              <%= form.label :date, style: "display: block", class: "mb-2" %>
              <%= form.date_field :date, class: "w-100 rounded py-2 py-md-3 border px-2", value: Time.now.strftime('%Y-%m-%d') %>
            </div>
            <div class="d-block">
              <%= form.label :time, style: "display: block", class: "mb-2" %>
              <%= form.time_field :time, class: "rounded py-2 py-md-3 border px-2", value: Time.now.strftime("%H:%M") %>
            </div>
      
            </div>

            <h5 class="mt-5">Add Drink</h5>
            <div class="mt-3">
              <div class="align-items-center my-3">
                <%= form.label :name, class: "mb-2" %>
                <%= form.text_field :name, class: "form-control" %>
              <div class="d-flex align-items-center mb-3">
              </div>
            </div>
          </div>
          <div class="mt-5">
            <%= form.label :comment, class: "mb-2 rounded" %>
            <%= form.rich_text_area :comment, rows:5, class: "form-control rounded w-100" %>
          </div>

           <div class="d-flex mt-5 align-items-center justify-content-around">
              <%= link_to "Cancel", entries_path, class:"cancel-button mt-4 border-0 bg-transparent fw-bold px-5 py-3 rounded-pill" %>
              <%= form.submit "Save", class:"mt-4 border px-5 py-3 fw-bold rounded-pill bgPr text-white" %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/drinks/edit.html.erb
<%= render "form", drink: @drink %>

app/views/drinks/index.html.erb
<%= notice %>
<header class="text-center header w-100 medication px-4 text-light d-flex justify-content-between align-items-center">
  <p class="mb-0"> <%= link_to '<i class="text-white fa-solid fa-arrow-left"></i>'.html_safe, entries_path %></p>        <p class="mb-0 mx-auto d-flex align-items-center text-white">
  <%= svg_tag "Drink", class: "form-icon"%>
  <span>Drink</span>
</p>
</header>

<div id="drinks">
  <% @drinks.each do |drink| %>
    <%= render drink %>
  <% end %>
</div>

app/views/drinks/new.html.erb
<%= notice %>
<%= render "form", drink: @drink %>

app/views/drinks/show.html.erb
<div class="position-relative">
  <p style="color: green"><%= notice %></p>

  <%= render @drink %>

  <div class="position-absolute action-btn d-flex justify-content-between">
  <%= link_to '<i class="fa-solid fa-pencil mr-2"></i>'.html_safe, edit_drink_path(@drink) %>
  <%= button_to '<i class="fa-solid fa-trash"></i>'.html_safe, drink_path(@drink), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
   <%= link_to '<i class="fa-solid fa-arrow-rotate-left"></i>'.html_safe, timeline_path %>
  </div>
</div