config/routes.rb
Rails.application.routes.draw do
  get '/entries', to: 'entries#index'
  get 'pages/index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/timeline', to: 'users#timeline', as: 'timeline'
  get '/symptoms_analysis', to: 'users#insight', as: 'symptom_analysis'
  get '/popup', to: 'users#popup'
  get '/hovercard', to: 'users#hovercard', as: 'hovercard'
  resources :symptoms
  resources :medications
  resources :moods
  resources :foods
  resources :drinks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name # assuming the user model has a name
      user.avatar_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  has_many :symptoms, dependent: :destroy
  has_many :medications, dependent: :destroy
  has_many :moods, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :drinks, dependent: :destroy
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    user = User.from_omniauth(auth)

    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect user, event: :authentication
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private

  # def from_google_params
  #   @from_google_params ||= {
  #     uid: auth.uid,
  #     email: auth.info.email,
  #     full_name: auth.info.name,
  #     avatar_url: auth.info.image
  #   }
  # end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def hovercard
    render 'hovercard'
  end

  def show
    @user = User.find(params[:id])
    @symptom = Symptom.find(params[:id])
  end

  def timeline
    @sympton_name = SymptomsController.new.columns
    @items = current_user.symptoms.order(created_at: :asc)
    @items += current_user.drinks.order(created_at: :asc)
    @items += current_user.foods.order(created_at: :asc)
    @items += current_user.medications.order(created_at: :asc)
    @items += current_user.moods.order(created_at: :asc)
    @items = @items.sort_by(&:created_at)
  end

  def insight
    render 'insight'
  end

  def popup
    render 'popup'
  end
end

app/views/users/hovercard.html.erb
<%= turbo_frame_tag dom_id(current_user, :thumbnail) do %>
  <div class="">
    <% @items.each do |item| %>
      <% if item.is_a?(Symptom) %>
        <small><%= time_ago_in_words(item.created_at) %> ago </small>
        <div class="d-flex justify-content-between align-items-center">
          <%= link_to "Edit", edit_symptom_path(item), class:"editbtn" %>
          <div class="deletebtn">
            <%= button_to "Delete", symptom_path(item), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/insight.html.erb
<div class="sign-head" data-target="view.analysis">
  <div class="bg-white d-flex flex-column align-items-center justify-content-center">
    <%= svg_tag 'coming_soon' %>
    <p>Coming Soon</p>
  </div>

<div class="add-item">
  <div class="add">
    <%= link_to '<i class="text-white fa-solid fa-plus"></i>'.html_safe, entries_path, class: "go-to-entries position-fixed border-0"%>
  </div>
</div>

app/views/users/popup.html.erb
<%= turbo_frame_tag "modal" do %>
   <%= tag.div data: { controller: "modal",
                      modal_target: "modal",
                      action: "turbo:submit-end->modal#submitEnd keyup@window->modal#closeWithKeyboard click@window->modal#closeBackground" },
                      class: "popup" do %>
    <div class="">
      <%= button_tag '<i class="fa-sharp fa-solid fa-xmark"></i>'.html_safe, data: { action: "modal#hideModal" }, type: "button", class: "close-btn" %>
     <ul class="navlist pl-0" aria-expanded="false" data-toggle-target="ariaExpander" data-toggle-close="true">
      <% if current_user %>
        <div class="name mt-0">
          <div class="more-data">
            <div class="mb-2 d-flex align-items-center">
              <%= svg_tag "Profile", class: "img" %> <h4><%= link_to "#{current_user.full_name}", class: "name" %></h4>
            </div>
          </div>
        </div>
        <div class="more-data d-flex align-items-center">
          <div>
            <p><%= link_to "My profile ", edit_user_registration_path, class: 'profile' %></p>
            <p><%= link_to "Home", root_path, class: 'profile' %></p>
            <p><%= link_to "Export data" %></p>
            <p><%= link_to "Privacy & Terms" %></p>
          </div>
        </div>
        <li class="account text-center pt-2"><%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "text-dark" %></li>
        <% else %>
        <li class="account text-center pt-2"> <%= link_to 'Sign in', user_session_path, class: "" %></li>
      <% end %>
    <ul>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="position-relative">
  <div class="sign-head">
    <%= render "layouts/menu_bar" %>
      <div class='d-flex gap-2 gap-md-4 justify-content-between'>
        <div class="d-flex align-items-center active-link w-50 active">
          <%= svg_tag 'Timeline_Selected', class: "timeline" %>
          <%= link_to 'Timeline', user_timeline_path(current_user), class: "time-insight py-3" %>
        </div>
        <div class="d-flex align-items-center active-rink">
          <%= svg_tag 'Insights_Selected', class: "timeline" %>
          <%= link_to 'Insight', entries_insight_path, class: "time-insight py-3" %>
        </div>
      </div>
    </div>
  </div>

  <% @items.each do |item| %>
    <% if item.is_a?(Symptom) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body p-4 hoverWrapper">
                      <%= svg_tag "Symptom", class: "show-icon"%>
                      <h6 class="datetime text-dark">Symptom</h6>
                      <% @sympton_name.each do |name| %>
                      <p class="item-name"><%= name %></p>
                      <% end %>
                      <article class="d-flex flex-column align-items-center position-absolute datetime">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Food) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body p-4 hoverWrapper">
                      <%= svg_tag "Food", class: "show-icon"%>
                      <h6 class="datetime text-dark">Food</h6>
                      <p class="item-name"><%= item.name %></p>
                      <article class="d-flex flex-column align-items-center position-absolute datetime">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Drink) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body p-4 hoverWrapper">
                      <%= svg_tag "Drink", class: "show-icon"%>
                      <h6 class="datetime text-dark">Drink</h6>
                      <p class="item-name"><%= item.name %></p>
                      <article class="position-absolute flex-column datetime d-flex align-items-center">
                        <div><%#= item.date.to_formatted_s(:rfc822) %></div>
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Medication) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body p-4 hoverWrapper">
                      <%= svg_tag "Medication", class: "show-icon"%>
                      <h6 class="datetime text-dark">Medication</h6>
                      <p class="item-name"><%= item.name %></p>
                      <article class="position-absolute flex-column datetime d-flex align-items-center">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Mood) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body p-4 hoverWrapper">
                      <%= svg_tag "Mood", class: "show-icon"%>
                      <h6 class="datetime text-dark">Mood</h6>
                      <p class="item-name"><%= item.mood %></p>
                      <article class="position-absolute flex-column datetime d-flex align-items-center">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
          </section>
        </div>
      </div>
    <% end %>   
  <% end %> 
  <%= link_to '<i class="text-white fa-solid fa-plus"></i>'.html_safe, entries_index_path, class: "go-to-entries position-fixed border-0"%>
</div>

app/views/users/timeline.html.erb
<div class="position-relative" data-target="view.timeline">
  <div class="sign-head">
    <%= render "layouts/menu_bar" %>
      <div class='d-flex gap-2 gap-md-4 justify-content-between'>
        <div class="d-flex align-items-center active-link w-50 active">
          <%= svg_tag 'Timeline_Selected', class: "timeline" %>
          <%= link_to 'Timeline', timeline_path, data: { controller: "view", action: "click->view#showTimeline" }, class: "time-insight py-3" %>
        </div>
        <div class="d-flex align-items-center active-rink">
          <%= svg_tag 'Insights_Selected', class: "timeline" %>
          <%= link_to 'Insight', symptom_analysis_path,  data: { controller: "view", action: "click->view#showAnalysis" }, class: "time-insight py-3" %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '<i class="text-white fa-solid fa-plus"></i>'.html_safe, timeline_path, class: "go-to-entries position-fixed border-0" %>
</div>

<div class="mx-5">
  <% @items.each do |item| %>
    <% if item.is_a?(Symptom) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body hoverWrapper">
                      <%= svg_tag "Symptom", class: "show-icon"%>
                      <div class="d-flex align-items-center">
                        <h6 class="datetime text-dark">Symptom</h6>
                        <%= button_to '<i class="fa-solid mx-2 fa-trash"></i>'.html_safe, symptom_path(item), class:'delete', method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
                      </div>
                      <% @sympton_name.each do |name| %>
                      <p class="item-name"><%= name %></p>
                      <% end %>
                      <article class="d-flex flex-column align-items-center position-absolute datetime">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Food) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body hoverWrapper">
                      <%= svg_tag "Food", class: "show-icon"%>
                      <div class="d-flex align-items-center">
                        <h6 class="datetime text-dark">Food</h6>
                        <%= button_to '<i class="fa-solid mx-2 fa-trash"></i>'.html_safe, food_path(item), class:'delete', method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
                      </div>
                      <p class="item-name"><%= item.name %></p>
                      <article class="d-flex flex-column align-items-center position-absolute datetime">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Drink) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body hoverWrapper">
                      <%= svg_tag "Drink", class: "show-icon"%>
                      <div class="d-flex align-items-center">
                        <h6 class="datetime text-dark">Drink</h6>
                        <%= button_to '<i class="fa-solid mx-2  fa-trash"></i>'.html_safe, drink_path(item), class:'delete', method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
                      </div>
                      <p class="item-name"><%= item.name %></p>
                      <article class="position-absolute flex-column datetime d-flex align-items-center">
                        <div><%#= item.date.to_formatted_s(:rfc822) %></div>
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Medication) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body hoverWrapper">
                      <%= svg_tag "Medication", class: "show-icon"%>
                      <div class="d-flex align-items-center">
                        <h6 class="datetime text-dark">Medication</h6>
                        <%= button_to '<i class="fa-solid mx-2  fa-trash"></i>'.html_safe, medication_path(item), class:'delete', method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
                      </div>
                      <p class="item-name"><%= item.name %></p>
                      <article class="position-absolute flex-column datetime d-flex align-items-center">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% elsif item.is_a?(Mood) %>
      <div class ="syptom_div">
        <div class ="symptom_data">
          <section class="gradient-custom-5">
            <div class="container">
              <div class="main-timeline-5">
                <div class="timeline-5 right-5">
                  <div class="">
                    <div class="card-body hoverWrapper">
                      <%= svg_tag "Mood", class: "show-icon"%>
                      <div class="d-flex align-items-center">
                        <h6 class="datetime text-dark">Mood</h6>
                        <%= button_to '<i class="fa-solid mx-2  fa-trash"></i>'.html_safe, mood_path(item), class:'delete', method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
                      </div>
                      <p class="item-name"><%= item.mood %></p>
                      <article class="position-absolute flex-column datetime d-flex align-items-center">
                        <p class="item-name"><%= item.time.strftime("%I:%M%p") %></p>
                      </article>
                      <p class="mt-2 mb-0"><%= item.comment %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    <% end %>   
  <% end %>
</div>