config/routes.rb
Rails.application.routes.draw do
  get '/entries', to: 'entries#index'
  get 'pages/index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/timeline', to: 'users#timeline', as: 'timeline'
  get '/symptoms_analysis', to: 'users#insight', as: 'symptom_analysis'
  get '/popup', to: 'users#popup'
  get '/hovercard', to: 'users#hovercard', as: 'hovercard'
  resources :symptoms
  resources :medications
  resources :moods
  resources :foods
  resources :drinks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
end

app/models/food.rb
class Food < ApplicationRecord
  has_rich_text :comment
  belongs_to :user
  validates :name, presence: true
  EDITABLE_ATTRS = %i[comment name date time].freeze
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /foods or /foods.json
  def index
    @foods = Food.all.order('created_at DESC').where(user: current_user)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @user = current_user
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @user = current_user
    @food = @user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to timeline_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to timeline_path, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to timeline_path, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :comment, :time, :date, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<section class="gradient-custom-5">
  <div class="container">
    <div class="main-timeline-5">
      <div class="timeline-5 right-5">
        <div class="">
          <div class="card-body p-4">
            <%= svg_tag "Food", class: "show-icon"%>
            <h5 class="card-title">Food</h5>
            <h5><%= food.name %></h5>
            <span class="small text-muted"><i class="fas fa-clock me-1"></i><%= food.date.strftime("%F") %>|<%= food.time.strftime("%H:%M") %></span>
            <p class="mt-2 mb-0"><%= food.comment %></p>
            <%= link_to "View Details", food, class: "view btn btn-primary" %>          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/foods/_form.html.erb
<div id="<%= dom_id food %>">
  <%= form_with(model: food) do |form|%>
    <% if food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
        <div class="col-md-8 mx-auto pb-5 bg-light">
            <header class="text-center header w-100 medication px-4 text-light d-flex justify-content-between align-items-center">
              <p class="mb-0"> <%= link_to '<i class="text-white fa-solid fa-arrow-left"></i>'.html_safe, timeline_path %></p>
              <p class="mb-0 mx-auto d-flex align-items-center text-white">
              <%= svg_tag "Food", class: "form-icon"%>
              <span>Meal/Food</span>
            </p>
            </header>
            <div class="px-4 pb-4 pt-4 d-flex flex-column flex-md-row justify-content-md-between">
              <div class="flex-child-cont px-5">
                <div class="d-flex justify-content-between">
                <div class="d-block">
                  <%= form.label :date, style: "display: block", class: "mb-2" %>
                  <%= form.date_field :date, class: "w-100 rounded py-2 py-md-3 border px-2", value: Time.now.strftime('%Y-%m-%d') %>
                </div>
                <div class="d-block">
                  <%= form.label :time, style: "display: block", class: "mb-2" %>
                  <%= form.time_field :time, class: "rounded py-2 py-md-3 border px-2", value: Time.now.strftime("%H:%M") %>
                </div>
               
                </div>

                <h5 class="mt-5">Add Food</h5>
                <div class="mt-3">
                  <div class="align-items-center my-3">
                    <%= form.label :name, class: "mb-2" %>
                    <%= form.text_field :name, class: "form-control" %>
                  <div class="d-flex align-items-center mb-3">
                  </div>
                </div>
              </div>
              <div class="mt-5">
                <%= form.label :comment, class: "mb-2 rounded" %>
                <%= form.rich_text_area :comment, rows:5, class: "form-control rounded w-100" %>
              </div>
              
              <div class="d-flex mt-5 align-items-center justify-content-around">
                <%= link_to "Cancel", entries_path, class:"cancel-button" %>
                <%= form.submit "Save", class:"mt-4 border px-5 py-3 fw-bold rounded-pill bgPr text-white" %>
              </div>
            </div>
      </div>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<%= render "form", food: @food %>

app/views/foods/index.html.erb
<header class="text-center header w-100 medication px-4 text-light d-flex justify-content-between align-items-center">
  <p class="mb-0"> <%= link_to '<i class="text-white fa-solid fa-arrow-left"></i>'.html_safe, timeline_path %></p>
  <p class="mb-0 mx-auto d-flex align-items-center text-white">
    <%= svg_tag "Food", class: "form-icon"%>
    <span>Meal/Food</span>
  </p>
</header>
<div id="foods">
  <% @foods.each do |food| %>
    <%= render food %>
  <% end %>
</div>

app/views/foods/new.html.erb
<%= notice %>
<%= render "form", food: @food %>

app/views/foods/show.html.erb
<div class="position-relative">
  <p style="color: green"><%= notice %></p>

  <%= render @food %>

  <div class="position-absolute action-btn d-flex justify-content-between">
  <%= link_to '<i class="fa-solid fa-pencil mr-2"></i>'.html_safe, edit_food_path(@food) %>
  <%= button_to '<i class="fa-solid fa-trash"></i>'.html_safe, food_path(@food), method: :delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>
  <%= link_to '<i class="fa-solid fa-arrow-rotate-left"></i>'.html_safe, timeline_path %>
  </div>
<div>